"""
ml_engine_bert.py  —  ScamShield ETFF-Net Inference Engine
============================================================
Integrates the p3.ipynb ETFF-Net model (IEEE-grade):
    DistilRoBERTa (fine-tuned, 768-dim CLS) +
    TF-IDF word (10k) + char (5k) n-grams +
    14 structural metadata features
    → Attention-fused → SelectKBest (5000) → LightGBM

Achieves: Accuracy=98.7%, F1=0.849, ROC-AUC=0.990
Threshold: 0.3792 (optimised for recall on fraud class)

Model artifacts (generated by p3.ipynb training run):
    etff_lgb_model.pkl      — LightGBM classifier
    etff_roberta.pt         — Fine-tuned DistilRoBERTa weights
    etff_tfidf_word.pkl     — Word TF-IDF (1-3 grams, 10k features)
    etff_tfidf_char.pkl     — Char TF-IDF (3-5 grams, 5k features)
    etff_selector.pkl       — SelectKBest (k=5000, mutual info)
    etff_threshold.pkl      — Optimal F1 decision threshold (0.3792)
    etff_scaler_bert.pkl    — StandardScaler for RoBERTa embeddings
    etff_scaler_tfidf.pkl   — StandardScaler for TF-IDF features
    etff_scaler_meta.pkl    — StandardScaler for metadata features
    etff_attn_weights.pkl   — Learned attention fusion weights [w_bert, w_tfidf, w_meta]

Lazy loading: heavy models load only on first prediction call so
api.py starts up quickly even on CPU-only deployments.
"""

import os
import re
import pickle

try:
    import numpy as np
except ImportError:
    np = None

# ── Artifact paths ────────────────────────────────────────────────────────────
_BASE = os.path.dirname(os.path.abspath(__file__))

_PATHS = {
    "lgb":          os.path.join(_BASE, "etff_lgb_model.pkl"),
    "roberta_pt":   os.path.join(_BASE, "etff_roberta.pt"),
    "tfidf_word":   os.path.join(_BASE, "etff_tfidf_word.pkl"),
    "tfidf_char":   os.path.join(_BASE, "etff_tfidf_char.pkl"),
    "selector":     os.path.join(_BASE, "etff_selector.pkl"),
    "threshold":    os.path.join(_BASE, "etff_threshold.pkl"),
    "scaler_bert":  os.path.join(_BASE, "etff_scaler_bert.pkl"),
    "scaler_tfidf": os.path.join(_BASE, "etff_scaler_tfidf.pkl"),
    "scaler_meta":  os.path.join(_BASE, "etff_scaler_meta.pkl"),
    "attn_w":       os.path.join(_BASE, "etff_attn_weights.pkl"),
}

# ── Lazy-loaded state ─────────────────────────────────────────────────────────
_loaded       = False
_available    = True   # set to False permanently if load fails

_lgb          = None
_tokenizer    = None
_roberta      = None
_device       = None
_tfidf_word   = None
_tfidf_char   = None
_selector     = None
_threshold    = 0.3792  # default from notebook output
_scaler_bert  = None
_scaler_tfidf = None
_scaler_meta  = None
_attn_w       = None   # np.array([w_bert, w_tfidf, w_meta])


# ── Text cleaner (mirrors p3.ipynb cell 4) ────────────────────────────────────
def _clean(text: str) -> str:
    text = str(text).lower()
    text = re.sub(r"http\S+", " ", text)
    text = re.sub(r"[^a-zA-Z ]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


# ── Metadata extractor for a raw text string ─────────────────────────────────
# At inference time we only have raw text (no structured DataFrame row),
# so we derive what we can: description length, presence of certain signals.
def _extract_meta_from_text(text: str) -> np.ndarray:
    """
    Returns a 14-dim feature vector that mirrors p3.ipynb's extract_metadata().
    Missing structured fields (logo, salary range, employment type) are
    imputed conservatively (0 = absent / unknown).
    """
    t = text.lower()
    desc_len    = len(text)
    profile_len = 0   # not extractable from raw post text
    req_len     = len(re.findall(r"(?:require|must have|qualification|experience)", t)) * 80

    features = [
        0,          # has_logo — unknown at inference, conservative=0
        1 if re.search(r"\?|apply now|send cv|send resume", t) else 0,  # has_questions proxy
        1 if re.search(r"\$|₹|£|salary|stipend|ctc|lpa|usd|inr", t) else 0,  # has_salary
        1 if re.search(r"experience|year[s]?\s+of", t) else 0,                # has_experience
        1 if re.search(r"degree|bachelor|master|b\.?tech|mba|diploma", t) else 0,  # has_education
        1 if "full-time" in t or "full time" in t else 0,   # emp_full_time
        1 if "part-time" in t or "part time" in t else 0,   # emp_part_time
        1 if "contract" in t else 0,                         # emp_contract
        1 if "temporary" in t or "temp " in t else 0,       # emp_temporary
        0.0,  # desc_len  — will be normalised below
        0.0,  # profile_len — unavailable
        0.0,  # req_len
        1 if desc_len < 100 else 0,                          # very_short_desc
        1 if profile_len == 0 else 0,                        # no_company_profile
    ]

    # Normalise length features (positions 9,10,11)
    features[9]  = desc_len    / 3000.0   # rough normalisation
    features[10] = profile_len / 1000.0
    features[11] = req_len     / 500.0

    return np.array(features, dtype=float).reshape(1, -1)


# ── Loader ────────────────────────────────────────────────────────────────────
def _load_all():
    """Load all ETFF-Net artifacts once. Thread-safe via global flag."""
    global _loaded, _available
    global _lgb, _tokenizer, _roberta, _device
    global _tfidf_word, _tfidf_char, _selector, _threshold
    global _scaler_bert, _scaler_tfidf, _scaler_meta, _attn_w

    if _loaded or not _available:
        return

    # Check required sklearn/pickle artifacts first (fast check)
    required_pkl = ["lgb", "tfidf_word", "tfidf_char", "selector",
                    "scaler_bert", "scaler_tfidf", "scaler_meta", "attn_w"]
    for key in required_pkl:
        if not os.path.exists(_PATHS[key]):
            print(f"[ETFF-Net] Artifact missing: {_PATHS[key]} — run p3.ipynb to train first.")
            _available = False
            return

    try:
        with open(_PATHS["lgb"],          "rb") as f: _lgb          = pickle.load(f)
        with open(_PATHS["tfidf_word"],   "rb") as f: _tfidf_word   = pickle.load(f)
        with open(_PATHS["tfidf_char"],   "rb") as f: _tfidf_char   = pickle.load(f)
        with open(_PATHS["selector"],     "rb") as f: _selector     = pickle.load(f)
        with open(_PATHS["scaler_bert"],  "rb") as f: _scaler_bert  = pickle.load(f)
        with open(_PATHS["scaler_tfidf"], "rb") as f: _scaler_tfidf = pickle.load(f)
        with open(_PATHS["scaler_meta"],  "rb") as f: _scaler_meta  = pickle.load(f)
        with open(_PATHS["attn_w"],       "rb") as f: _attn_w       = pickle.load(f)

        if os.path.exists(_PATHS["threshold"]):
            with open(_PATHS["threshold"], "rb") as f:
                _threshold = pickle.load(f)

        print(f"[ETFF-Net] Sklearn artifacts loaded. Threshold={_threshold:.4f}")
    except Exception as e:
        print(f"[ETFF-Net] Failed to load sklearn artifacts: {e}")
        _available = False
        return

    # Load DistilRoBERTa (heavy — loaded last)
    if not os.path.exists(_PATHS["roberta_pt"]):
        print("[ETFF-Net] etff_roberta.pt missing — embedding from TF-IDF only (degraded mode).")
        _loaded = True
        return

    try:
        import torch
        from transformers import RobertaTokenizer, RobertaForSequenceClassification

        _device    = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        _tokenizer = RobertaTokenizer.from_pretrained("distilroberta-base")
        _roberta   = RobertaForSequenceClassification.from_pretrained(
            "distilroberta-base", num_labels=2
        ).to(_device)
        _roberta.load_state_dict(
            torch.load(_PATHS["roberta_pt"], map_location=_device), strict=False
        )
        _roberta.eval()
        print(f"[ETFF-Net] DistilRoBERTa loaded on {_device}")
    except Exception as e:
        print(f"[ETFF-Net] RoBERTa load failed (TF-IDF-only fallback): {e}")
        _roberta = None   # degraded mode — still works via TF-IDF path

    _loaded = True


# ── CLS embedding extraction ──────────────────────────────────────────────────
def _get_roberta_embedding(text: str) -> np.ndarray:
    """Returns (1, 768) CLS embedding from fine-tuned DistilRoBERTa."""
    import torch
    enc = _tokenizer(
        text[:512],
        max_length=128,
        padding="max_length",
        truncation=True,
        return_tensors="pt"
    )
    enc = {k: v.to(_device) for k, v in enc.items()}
    with torch.no_grad():
        out = _roberta.roberta(
            input_ids=enc["input_ids"],
            attention_mask=enc["attention_mask"]
        )
    cls = out.last_hidden_state[:, 0, :].cpu().numpy()  # (1, 768)
    return cls


# ── Public API ────────────────────────────────────────────────────────────────
def is_model_ready() -> bool:
    """Returns True if the core LightGBM model artifacts exist."""
    return all(os.path.exists(_PATHS[k])
               for k in ["lgb", "tfidf_word", "tfidf_char", "selector",
                          "scaler_bert", "scaler_tfidf", "scaler_meta", "attn_w"])


def predict_bert(text: str) -> float | None:
    """
    Run ETFF-Net inference on raw job posting text.

    Returns:
        float  — scam probability in [0.0, 1.0]
        None   — if model artifacts are not available
    """
    _load_all()
    if not _available or _lgb is None:
        return None

    try:
        cleaned = _clean(text)

        # ── 1. TF-IDF features ───────────────────────────────────────────────
        tfidf_w = _tfidf_word.transform([cleaned]).toarray()  # (1, 10000)
        tfidf_c = _tfidf_char.transform([cleaned]).toarray()  # (1, 5000)
        tfidf   = np.hstack([tfidf_w, tfidf_c])               # (1, 15000)

        # ── 2. RoBERTa embedding ─────────────────────────────────────────────
        if _roberta is not None:
            bert_emb = _get_roberta_embedding(cleaned)         # (1, 768)
        else:
            # Degraded: substitute zeros (model still runs via TF-IDF)
            bert_emb = np.zeros((1, 768), dtype=np.float32)

        # ── 3. Structural metadata ───────────────────────────────────────────
        meta = _extract_meta_from_text(text)                   # (1, 14)

        # ── 4. Scale each feature group ──────────────────────────────────────
        bert_n  = _scaler_bert.transform(bert_emb)
        tfidf_n = _scaler_tfidf.transform(tfidf)
        meta_n  = _scaler_meta.transform(meta)

        # ── 5. Attention fusion (learned weights from p3.ipynb) ───────────────
        w = np.array(_attn_w, dtype=float).flatten()
        if len(w) < 3:
            w = np.array([0.29, 0.34, 0.37])  # notebook output defaults

        fused = np.hstack([
            bert_n  * w[0],
            tfidf_n * w[1],
            meta_n  * w[2]
        ])                                                      # (1, 15782)

        # ── 6. Feature selection (k=5000) ─────────────────────────────────────
        selected = _selector.transform(fused)                  # (1, 5000)

        # ── 7. LightGBM inference ─────────────────────────────────────────────
        proba = _lgb.predict_proba(selected)[0]
        classes = list(_lgb.classes_)
        idx = classes.index(1) if 1 in classes else 1
        prob = float(proba[idx])

        return prob

    except Exception as e:
        print(f"[ETFF-Net] Prediction error: {e}")
        return None
